### ISSUE TITLE
running `nbqa` from command-line

### ISSUE THREAD

**Issue by amor71** [nbQA-dev/nbQA#412]
throws an exception:
```python-traceback
Traceback (most recent call last):
  File "/Users/amichayoren/venv/algo/lib/python3.8/site-packages/nbqa/cmdline.py", line 127, in parse_args
    args, cmd_args = parser.parse_known_args(raw_args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 2034, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 2520, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 2507, in exit
    _sys.exit(status)
SystemExit: 2
```

**Comment by MarcoGorelli** [comment]
Hi @amor71 

Thanks for the report! Could you please share which command you ran?

**Comment by amor71** [comment]
Just typed ‘nbqa’ in the command-line . Thank you for the quick response

**Comment by MarcoGorelli** [comment]
Happy to help!

In the future, please include the full traceback when reporting an issue.

In the README there are some examples of how to run `nbqa` from the command-line, see https://github.com/nbQA-dev/nbQA#command-line

Closing then as it doesn't look like there's anything we need to do here, but please do let us know if you run into issues!

**Comment by amor71** [comment]
I suggest to show usage message(/error message if needed) and not an
exception w/ traceback... but ur call. .

**Comment by MarcoGorelli** [comment]
That's a good point, maybe the traceback is too long and not helpful...reopening then, thanks for the feedback!

**Comment by s-weigand** [comment]
Maybe we can get some inspiration from tools like `grep` or `git`.
```console
$ grep
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

```console
$ git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add               Add file contents to the index
   mv                Move or rename a file, a directory, or a symlink
   restore           Restore working tree files
   rm                Remove files from the working tree and from the index
   sparse-checkout   Initialize and modify the sparse-checkout

examine the history and state (see also: git help revisions)
   bisect            Use binary search to find the commit that introduced a bug
   diff              Show changes between commits, commit and working tree, etc
   grep              Print lines matching a pattern
   log               Show commit logs
   show              Show various types of objects
   status            Show the working tree status

grow, mark and tweak your common history
   branch            List, create, or delete branches
   commit            Record changes to the repository
   merge             Join two or more development histories together
   rebase            Reapply commits on top of another base tip
   reset             Reset current HEAD to the specified state
   switch            Switch branches
   tag               Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch             Download objects and refs from another repository
   pull              Fetch from and integrate with another repository or a local branch
   push              Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.
```

So there are 2 ways:
1. Just show usage and tell the user to call `--help` for more information
1. Show usage + a list of subcommands (supported tools in our case) and refer to help.

**Comment by Daniel-Mietchen** [comment]
Either of the two options would be fine (and better than the current behavior), with the ```grep``` variant probably a bit easier on the development side and the ```git``` one a bit more comfortable for the user.

**Comment by MarcoGorelli** [comment]
Thanks all for your feedback - how about this?

```console
$ nbqa
usage: nbqa <code quality tool> <notebook or directory> <flags>

Please specify:
- 1) a code quality tool
- 2) some notebooks (or, if supported by the tool, directories)
- 3) (optional) extra flags

Examples:
    nbqa black notebook.ipynb
    nbqa black notebook.ipynb --line-length=96
    nbqa black notebook_1.ipynb notebook_2.ipynb

If you want to let `nbqa` modify your notebook(s), also pass `--nbqa-mutate`:
    nbqa black notebook.ipynb --nbqa-mutate

See https://nbqa.readthedocs.io/en/latest/index.html for more details on how to run `nbqa`.
nbqa: error: the following arguments are required: command, root_dirs
```

**Comment by MarcoGorelli** [comment]
@all-contributors please add @amor71 for ideas

**Comment by MarcoGorelli** [comment]
The latest release (0.4.0) shows
```console
$ nbqa
usage: nbqa <code quality tool> <notebook or directory> <nbqa options> <code quality tool arguments>

Please specify:
- 1) a code quality tool (e.g. `black`, `pyupgrade`, `flake`, ...)
- 2) some notebooks (or, if supported by the tool, directories)
- 3) (optional) flags for nbqa (e.g. `--nbqa-mutate`)
- 4) (optional) flags for code quality tool (e.g. `--line-length` for `black`)

Examples:
    nbqa flake8 notebook.ipynb
    nbqa black notebook.ipynb --line-length=96
    nbqa pyupgrade notebook_1.ipynb notebook_2.ipynb

Mutation: to let `nbqa` modify your notebook(s), also pass `--nbqa-mutate`, e.g.:
    nbqa black notebook.ipynb --nbqa-mutate

See https://nbqa.readthedocs.io/en/latest/index.html for more details on how to run `nbqa`.
nbqa: error: the following arguments are required: command, root_dirs
```
along with several other improvements.

Next big to-dos are:
- automatically detect when cell magics can be skipped, so we can extend support to custom cell magics defined via `%load_ext`
- add `--nbqa-diff`, which would make demoing the tool a whole lot easier

Daniel I know you're keen on the latter feature, we'll let you know when it's available, and now that some other issues have been resolved, the path is clear to do start implementing it!

Thanks all for your help in improving nbqa!
