### ISSUE TITLE
Issue when no cells present

### ISSUE THREAD

**Issue by henryiii** [nbQA-dev/nbQA#443]
I have a teaching repo and the first notebook has no code cells. So this breaks:

```
Traceback (most recent call last):
  File "/Users/henryschreiner/.cache/pre-commit/repoqkax9728/py_env-python3/lib/python3.9/site-packages/nbqa/__main__.py", line 524, in _run_on_one_root_dir
    nb_info_mapping[notebook] = save_source.main(
  File "/Users/henryschreiner/.cache/pre-commit/repoqkax9728/py_env-python3/lib/python3.9/site-packages/nbqa/save_source.py", line 368, in main
    result[-1] = result[-1].rstrip(NEWLINE)
IndexError: list index out of rang
```

**Comment by MarcoGorelli** [comment]
Hi @henryiii 

Thanks for the report, really appreciate it! I'll try to get a fix in this week

**Comment by henryiii** [comment]
This is the notebook if it helps: https://github.com/henryiii/python-compiled-minicourse/blob/master/00-intro.ipynb

**Comment by MarcoGorelli** [comment]
That's really helpful, thanks again!

@all-contributors please add @henryiii for bugs
