### ISSUE TITLE
How to execute doctests of a directory-tree?

### ISSUE THREAD

**Issue by agruenberger** [nbQA-dev/nbQA#530]
First, thank's for your project!! You did a  gatefull work.

I have a Question, a CahngeRequest or properbly a bug.

I whant to start a doctest of all Notebooks within a folder (recursivly)

Example: `!nbqa doctest /home/jovyan/work/mandanten/demo/DocTest/ToTest`   

But then a got a crasy stacktrace:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "/opt/conda/lib/python3.8/doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "/opt/conda/lib/python3.8/doctest.py", line 2055, in testfile
    text, filename = _load_testfile(filename, package, module_relative,
  File "/opt/conda/lib/python3.8/doctest.py", line 232, in _load_testfile
    with open(filename, encoding=encoding) as f:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmp4eum5sau/home/jovyan/work/mandanten/demo/DocTest/ToTest'
```
Why is it searching in a temp folder?

Thanks in advise
andy

**Comment by agruenberger** [comment]
Additional comment:
probably you need to imporve the documentation, for this usecase

**Comment by MarcoGorelli** [comment]
Hi @agruenberger 

Thanks for your comment!

The issue here is with `doctest` - if `doctest` doesn't work on directories, then neither will `nbqa doctest`

**Comment by MarcoGorelli** [comment]
e.g. this fails:
```python
$ python -m doctest pandas
Traceback (most recent call last):
  File "/home/marco/miniconda3/envs/pandas-dev/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/marco/miniconda3/envs/pandas-dev/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/marco/miniconda3/envs/pandas-dev/lib/python3.8/doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "/home/marco/miniconda3/envs/pandas-dev/lib/python3.8/doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "/home/marco/miniconda3/envs/pandas-dev/lib/python3.8/doctest.py", line 2055, in testfile
    text, filename = _load_testfile(filename, package, module_relative,
  File "/home/marco/miniconda3/envs/pandas-dev/lib/python3.8/doctest.py", line 232, in _load_testfile
    with open(filename, encoding=encoding) as f:
IsADirectoryError: [Errno 21] Is a directory: 'pandas'
```

**Comment by MarcoGorelli** [comment]
> Why is it searching in a temp folder?

That's how nbqa works, it makes a temporary copy of your notebook as a Python file and runs the tool you've given it. Reopening though because the error message should be parsed to reference the local directory rather than the temporary one, thanks for your report!

**Comment by MarcoGorelli** [comment]
@all-contributors please add @agruenberger for bug

**Comment by agruenberger** [comment]
Thanks for your fast response!

Sorry a have forgotten doctest does not work with directories.
At my company we use an other framework for pure python.

1. It's easy to implement a workaround
2. If i find a solution to integrate i will send you a pull resequest as a proposal.

first i need checkout the code ;-)

have a nice weekend 
greetings andy

**Comment by MarcoGorelli** [comment]
>  i will send you a pull resequest as a proposal.

that would be much appreciated, thank you!

**Comment by MarcoGorelli** [comment]
> Sorry a have forgotten doctest does not work with directories.

BTW, with the latest version of nbqa, you should be able to run `nbqa doctest` on a directory, and it'll run on all the `ipynb` files inside it
