### ISSUE TITLE
yapf hook not working for .toml projects

### ISSUE THREAD

**Issue by miguelcarcamov** [nbQA-dev/nbQA#723]
Hello,

I have a .toml project and when I run nbQA with yapf it tells me that I need to install the toml package. I have tried to added the additional dependency in the hook as:
```python
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
  - id: nbqa-yapf
    additional_dependencies: [toml]
```
But I get:
```python
Traceback (most recent call last):
  File "/home/miguel/.cache/pre-commit/repoo4r23pnd/py_env-python3.10/lib/python3.10/site-packages/nbqa/__main__.py", line 673, in _check_command_is_installed
    command_version = metadata.version(python_module)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 984, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for yapf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miguel/.cache/pre-commit/repoo4r23pnd/py_env-python3.10/lib/python3.10/site-packages/nbqa/__main__.py", line 676, in _check_command_is_installed
    import_module(python_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yapf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miguel/.cache/pre-commit/repoo4r23pnd/py_env-python3.10/bin/nbqa", line 8, in <module>
    sys.exit(main())
  File "/home/miguel/.cache/pre-commit/repoo4r23pnd/py_env-python3.10/lib/python3.10/site-packages/nbqa/__main__.py", line 704, in main
    _check_command_is_installed(cli_args.command)
  File "/home/miguel/.cache/pre-commit/repoo4r23pnd/py_env-python3.10/lib/python3.10/site-packages/nbqa/__main__.py", line 683, in _check_command_is_installed
    raise ModuleNotFoundError(_get_command_not_found_msg(command)) from exc
ModuleNotFoundError: Command `yapf` not found by nbqa.

Please make sure you have it installed in the same Python environment as nbqa. See
e.g. https://realpython.com/python-virtual-environments-a-primer/ for how to set up
a virtual environment in Python, and run:

    `python -m pip install yapf`.

```

**Comment by MarcoGorelli** [comment]
Hi @miguelcarcamov 

you'll need
```
additional_dependencies: [toml, yapf]
```
(better still to pin them)
